# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import pandas as pd
from PyQt5.QtWidgets import * 
from PyQt5 import QtWidgets
from PyQt5.QtGui import *
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt
import matplotlib as mpl 
mpl.rcParams['toolbar'] = 'None'
plt.style.use("dark_background")
for param in ['text.color', 'axes.labelcolor', 'xtick.color', 'ytick.color']:
    plt.rcParams[param] = '0.9'  # very light grey
for param in ['figure.facecolor', 'axes.facecolor', 'savefig.facecolor']:
    plt.rcParams[param] = '#212946'  # bluish dark grey
colors = [
    '#08F7FE',  # teal/cyan
    '#FE53BB',  # pink
    '#F5D300',  # yellow
    '#00ff41',  # matrix green
    '#fff', #White
]
from matplotlib.pyplot import figure as f
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_blood(object):
    def setupUi(self, blood):
        blood.setObjectName("blood")
        blood.setFixedSize(984, 861)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        blood.setWindowIcon(icon)
        blood.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(blood)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 991, 861))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(12, 17, 31);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 281, 181))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 80, 281, 181))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 281, 181))
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 460, 961, 391))
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 270, 281, 181))
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(590, 80, 381, 371))
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"border-radius:5px;\n"
"background-color: rgb(14, 22, 39);\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(700, 130, 151, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius:75px;\n"
"    \n"
"    background-image: url(:/profile/propic.png);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 90, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:gray;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(600, 280, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:#00aba9;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(600, 380, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(238,17,17,130);\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(227,162,26);\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(310, 90, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(43,87,151);\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 270, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(0,163,0);\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 270, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(238,17,17,130);\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(310, 130, 261, 121))
        self.listWidget.setStyleSheet("QListWidget\n"
"{\n"
"color:#fff;\n"
"background:Transparent;\n"
"border-radius:5px;\n"
"border:1px solid gray;\n"
"\n"
"}")
        self.listWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 130, 261, 121))
        self.lcdNumber.setStyleSheet("QLCDNumber\n"
"{\n"
"background:Transparent;\n"
"border: 1px solid gray;\n"
"border-radius:5px;\n"
"}")
        self.lcdNumber.setProperty("intValue", 156)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 320, 261, 121))
        self.lcdNumber_2.setStyleSheet("QLCDNumber\n"
"{\n"
"background:Transparent;\n"
"border: 1px solid gray;\n"
"border-radius:5px;\n"
"}")
        self.lcdNumber_2.setProperty("intValue", 62)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(310, 310, 261, 131))
        self.listWidget_2.setStyleSheet("QListWidget\n"
"{\n"
"color:#fff;\n"
"background:Transparent;\n"
"border-radius:5px;\n"
"border:1px solid gray;\n"
"\n"
"}")
        self.listWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWidget_2.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_2.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_2.addItem(item)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(600, 410, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(227,162,26,130);\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.control_2 = QtWidgets.QPushButton(self.centralwidget)
        self.control_2.setGeometry(QtCore.QRect(840, 410, 121, 31))
        self.control_2.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.control_2.setFont(font)
        self.control_2.setStyleSheet("QPushButton{\n"
"    color:#fff;\n"
"    \n"
"    background-color: rgb(0, 170, 127);\n"
"    border: 1px solid rgb(0,123,210);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 170, 127,50);\n"
"    border: 1px solid rgba(255,255,255,150);\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(0, 170, 127,100);\n"
"    border: 1px solid rgb(113, 113, 113);\n"
"}")
        self.control_2.setFlat(True)
        self.control_2.setObjectName("control_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 961, 31))
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    color:#fff;\n"
"    \n"
"    background-repeat: no-repeat;\n"
"    background-position: left;\n"
"    border:None;\n"
"    background-color: rgb(6, 9, 16);  border-radius:5px;\n"
" \n"
"    background-image: url(:/icons/images/find.png);\n"
"}")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 540, 241, 41))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/bookmark_document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 590, 241, 41))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/chart_pie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 640, 241, 41))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 790, 241, 41))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 480, 681, 371))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setStyleSheet("background-color: rgb(14, 22, 39);\n"
"\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: silver;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(0, 270, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(43,87,151);\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(230, 270, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:#00aba9;\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(440, 270, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(227,162,26);\n"
"}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.circularProgressBar_Main_2 = QtWidgets.QFrame(self.tab)
        self.circularProgressBar_Main_2.setGeometry(QtCore.QRect(10, 40, 240, 240))
        self.circularProgressBar_Main_2.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main_2.setObjectName("circularProgressBar_Main_2")
        self.circularProgressCPU = QtWidgets.QFrame(self.circularProgressBar_Main_2)
        self.circularProgressCPU.setGeometry(QtCore.QRect(-10, 10, 220, 220))
        self.circularProgressCPU.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.circularProgressCPU.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU.setObjectName("circularProgressCPU")
        self.circularContainer = QtWidgets.QFrame(self.circularProgressCPU)
        self.circularContainer.setGeometry(QtCore.QRect(15, 15, 190, 190))
        self.circularContainer.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer.setStyleSheet("QFrame{\n"
"    border-radius: 95px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer.setObjectName("circularContainer")
        self.labelPercentageCPU = QtWidgets.QLabel(self.circularContainer)
        self.labelPercentageCPU.setGeometry(QtCore.QRect(40, 50, 132, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.labelPercentageCPU.setFont(font)
        self.labelPercentageCPU.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.labelPercentageCPU.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentageCPU.setIndent(-1)
        self.labelPercentageCPU.setObjectName("labelPercentageCPU")
        self.circularProgressCPU_2 = QtWidgets.QFrame(self.tab)
        self.circularProgressCPU_2.setGeometry(QtCore.QRect(220, 50, 220, 220))
        self.circularProgressCPU_2.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.56 rgba(0, 171, 169,255), stop:0.559 rgba(255, 255, 255, 0));\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.circularProgressCPU_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU_2.setObjectName("circularProgressCPU_2")
        self.circularContainer_2 = QtWidgets.QFrame(self.circularProgressCPU_2)
        self.circularContainer_2.setGeometry(QtCore.QRect(15, 15, 190, 190))
        self.circularContainer_2.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_2.setStyleSheet("QFrame{\n"
"    border-radius: 95px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_2.setObjectName("circularContainer_2")
        self.labelPercentageCPU_2 = QtWidgets.QLabel(self.circularContainer_2)
        self.labelPercentageCPU_2.setGeometry(QtCore.QRect(40, 50, 132, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.labelPercentageCPU_2.setFont(font)
        self.labelPercentageCPU_2.setStyleSheet("color:#00aba9; padding: 0px; background-color: none;")
        self.labelPercentageCPU_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentageCPU_2.setIndent(-1)
        self.labelPercentageCPU_2.setObjectName("labelPercentageCPU_2")
        self.circularProgressCPU_3 = QtWidgets.QFrame(self.tab)
        self.circularProgressCPU_3.setGeometry(QtCore.QRect(440, 50, 220, 220))
        self.circularProgressCPU_3.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.68 rgba(227,162,26,255), stop:0.679 rgba(227,162,26,0));\n"
"}")
        self.circularProgressCPU_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU_3.setObjectName("circularProgressCPU_3")
        self.circularContainer_3 = QtWidgets.QFrame(self.circularProgressCPU_3)
        self.circularContainer_3.setGeometry(QtCore.QRect(15, 15, 190, 190))
        self.circularContainer_3.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_3.setStyleSheet("QFrame{\n"
"    border-radius: 95px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_3.setObjectName("circularContainer_3")
        self.labelPercentageCPU_3 = QtWidgets.QLabel(self.circularContainer_3)
        self.labelPercentageCPU_3.setGeometry(QtCore.QRect(40, 50, 132, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.labelPercentageCPU_3.setFont(font)
        self.labelPercentageCPU_3.setStyleSheet("color:rgb(227,162,26); padding: 0px; background-color: none;")
        self.labelPercentageCPU_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentageCPU_3.setIndent(-1)
        self.labelPercentageCPU_3.setObjectName("labelPercentageCPU_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        #self.widget_bloodgroup = QtWidgets.QWidget(self.tab_3)
        #self.widget_bloodgroup.setGeometry(QtCore.QRect(10, 10, 661, 321))
        #self.widget_bloodgroup.setObjectName("widget_bloodgroup")

        self.layout = QGridLayout(self.tab_3)
        self.layout.setGeometry(QtCore.QRect(10, 10, 661, 321))
        self.figure = plt.figure()
        f(figsize=(10, 6), dpi=100)
        self.canvas = FigureCanvas(self.figure)
        #self.layout.addWidget(self.btn_plot_graph)
        self.layout.addWidget(self.canvas)
        #self.layout.addWidget(self.canvas1)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.progressBar_1 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_1.setGeometry(QtCore.QRect(10, 290, 321, 21))
        self.progressBar_1.setStyleSheet("QProgressBar{\n"
"    background-color : rgb(141, 144, 147);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color:  #00aba9;\n"
"}")
        self.progressBar_1.setProperty("value", 85)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_1.setInvertedAppearance(False)
        self.progressBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_1.setObjectName("progressBar_1")
        self.temp_frame_3 = QtWidgets.QFrame(self.tab_2)
        self.temp_frame_3.setGeometry(QtCore.QRect(10, 30, 321, 241))
        self.temp_frame_3.setMinimumSize(QtCore.QSize(280, 180))
        self.temp_frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(75, 65, 130,50);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}")
        self.temp_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temp_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temp_frame_3.setObjectName("temp_frame_3")
        self.temp_frame_line_5 = QtWidgets.QFrame(self.temp_frame_3)
        self.temp_frame_line_5.setGeometry(QtCore.QRect(10, 35, 301, 2))
        self.temp_frame_line_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.temp_frame_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.temp_frame_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.temp_frame_line_5.setObjectName("temp_frame_line_5")
        self.temperature_label_5 = QtWidgets.QLabel(self.temp_frame_3)
        self.temperature_label_5.setGeometry(QtCore.QRect(50, 5, 211, 27))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setUnderline(False)
        self.temperature_label_5.setFont(font)
        self.temperature_label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.temperature_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature_label_5.setObjectName("temperature_label_5")
        self.battery_frame_7 = QtWidgets.QFrame(self.temp_frame_3)
        self.battery_frame_7.setGeometry(QtCore.QRect(110, 60, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battery_frame_7.sizePolicy().hasHeightForWidth())
        self.battery_frame_7.setSizePolicy(sizePolicy)
        self.battery_frame_7.setMinimumSize(QtCore.QSize(100, 100))
        self.battery_frame_7.setMaximumSize(QtCore.QSize(100, 100))
        self.battery_frame_7.setStyleSheet("QFrame{\n"
"    border: 6px solid #00aba9;\n"
"    border-radius: 50px;\n"
"}\n"
"\\\n"
"")
        self.battery_frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_frame_7.setObjectName("battery_frame_7")
        self.battery_percentage_output_label_7 = QtWidgets.QLabel(self.battery_frame_7)
        self.battery_percentage_output_label_7.setGeometry(QtCore.QRect(0, 37, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.battery_percentage_output_label_7.setFont(font)
        self.battery_percentage_output_label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none; \n"
"background-color: none;")
        self.battery_percentage_output_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.battery_percentage_output_label_7.setObjectName("battery_percentage_output_label_7")
        self.label_20 = QtWidgets.QLabel(self.temp_frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 210, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(227,162,26,130);\n"
"}")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.temp_frame_4 = QtWidgets.QFrame(self.tab_2)
        self.temp_frame_4.setGeometry(QtCore.QRect(340, 30, 321, 241))
        self.temp_frame_4.setMinimumSize(QtCore.QSize(280, 180))
        self.temp_frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(75, 65, 130,50);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}")
        self.temp_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temp_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temp_frame_4.setObjectName("temp_frame_4")
        self.temperature_label_6 = QtWidgets.QLabel(self.temp_frame_4)
        self.temperature_label_6.setGeometry(QtCore.QRect(50, 5, 211, 27))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setUnderline(False)
        self.temperature_label_6.setFont(font)
        self.temperature_label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.temperature_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature_label_6.setObjectName("temperature_label_6")
        self.battery_frame_8 = QtWidgets.QFrame(self.temp_frame_4)
        self.battery_frame_8.setGeometry(QtCore.QRect(110, 60, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battery_frame_8.sizePolicy().hasHeightForWidth())
        self.battery_frame_8.setSizePolicy(sizePolicy)
        self.battery_frame_8.setMinimumSize(QtCore.QSize(100, 100))
        self.battery_frame_8.setMaximumSize(QtCore.QSize(100, 100))
        self.battery_frame_8.setStyleSheet("QFrame{\n"
"    border: 6px solid rgb(43,87,151);\n"
"    border-radius: 50px;\n"
"}\n"
"")
        self.battery_frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_frame_8.setObjectName("battery_frame_8")
        self.battery_percentage_output_label_8 = QtWidgets.QLabel(self.battery_frame_8)
        self.battery_percentage_output_label_8.setGeometry(QtCore.QRect(0, 37, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.battery_percentage_output_label_8.setFont(font)
        self.battery_percentage_output_label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none; \n"
"background-color: none;")
        self.battery_percentage_output_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.battery_percentage_output_label_8.setObjectName("battery_percentage_output_label_8")
        self.temp_frame_line_6 = QtWidgets.QFrame(self.temp_frame_4)
        self.temp_frame_line_6.setGeometry(QtCore.QRect(10, 35, 301, 2))
        self.temp_frame_line_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.temp_frame_line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.temp_frame_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.temp_frame_line_6.setObjectName("temp_frame_line_6")
        self.label_21 = QtWidgets.QLabel(self.temp_frame_4)
        self.label_21.setGeometry(QtCore.QRect(10, 210, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel\n"
"{\n"
"background:None;\n"
"color:rgb(227,162,26,130);\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_2.setGeometry(QtCore.QRect(340, 290, 321, 21))
        self.progressBar_2.setStyleSheet("QProgressBar{\n"
"    background-color : rgb(141, 144, 147);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(43,87,151);\n"
"}")
        self.progressBar_2.setProperty("value", 67)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 690, 241, 41))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(720, 740, 241, 41))
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{\n"
"    color : #fff;\n"
"    \n"
"    background-color: rgb(0, 85, 127,80);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:Hover\n"
"{\n"
"    background-color: rgb(0, 85, 127,200);\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(0, 85, 127,180);\n"
"    \n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/exclamation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName("pushButton_6")
        blood.setCentralWidget(self.centralwidget)

        self.retranslateUi(blood)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(blood)
        self.pushButton_4.clicked.connect(lambda:blood.close())
    def retranslateUi(self, blood):
        _translate = QtCore.QCoreApplication.translate
        blood.setWindowTitle(_translate("blood", "BRACU BLOOD BANK V1.0"))
        self.label_9.setText(_translate("blood", "Donor Information"))
        self.label_10.setText(_translate("blood", "Name: Sihab Sahariar \n"
"Department: CSE\n"
"Semester: 4th\n"
" Phone Number : 01711715576"))
        self.label_11.setText(_translate("blood", "Blood Group : O+                        Age : 21 y/o"))
        self.label_12.setText(_translate("blood", "Total Donor"))
        self.label_13.setText(_translate("blood", "Recently Donated"))
        self.label_14.setText(_translate("blood", "Avilable Donor"))
        self.label_15.setText(_translate("blood", "Emergency Notification"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("blood", "Fatima Islam - 017XXXXXXXX - O+"))
        item = self.listWidget.item(1)
        item.setText(_translate("blood", "Rakib Hasan - 017XXXXXXXX - B+"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("blood", "Dhaka Medical: 01711XXXXX- B+"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("blood", "XYZ Medical: 01711XXXXX- O-"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("blood", "XYZ Hospital: 01711XXXXXX- AB+"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("blood", "Last Donate : 05/03/2021"))
        self.control_2.setText(_translate("blood", "History"))
        self.lineEdit.setPlaceholderText(_translate("blood", "Search A Donor"))
        self.pushButton.setText(_translate("blood", "Donation Rate"))
        self.pushButton_2.setText(_translate("blood", "Blood Group Graph"))
        self.pushButton_3.setText(_translate("blood", "Availability"))
        self.pushButton_4.setText(_translate("blood", "Exit"))
        self.label_17.setText(_translate("blood", "Male : 56%"))
        self.label_18.setText(_translate("blood", "Female: 44%"))
        self.label_19.setText(_translate("blood", "Accepted : 32%"))
        self.labelPercentageCPU.setText(_translate("blood", "<html><head/><body><p align=\"center\"><span style=\" font-size:50pt;\">56</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p></body></html>"))
        self.labelPercentageCPU_2.setText(_translate("blood", "<html><head/><body><p align=\"center\"><span style=\" font-size:50pt;\">44</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p></body></html>"))
        self.labelPercentageCPU_3.setText(_translate("blood", "<html><head/><body><p align=\"center\"><span style=\" font-size:50pt;\">32</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("blood", "Donation Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("blood", "Blood Group Graph"))
        self.temperature_label_5.setText(_translate("blood", "Male"))
        self.battery_percentage_output_label_7.setText(_translate("blood", "85%"))
        self.label_20.setText(_translate("blood", "Recently Donated : Fatima Islam"))
        self.temperature_label_6.setText(_translate("blood", "Female"))
        self.battery_percentage_output_label_8.setText(_translate("blood", "67%"))
        self.label_21.setText(_translate("blood", "Recently Donated : Rakib Hasan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("blood", "Availability"))
        self.pushButton_5.setText(_translate("blood", "Help"))
        self.pushButton_6.setText(_translate("blood", "About"))
        self.plot()
        
    def plot(self):
        self.figure.clear()
        ax = self.figure.add_subplot(111)
        df = pd.read_csv('blood.csv')
        fig = plt.subplots()
        df.plot(marker='o', color=colors, ax=ax)
        # Redraw the data with low alpha and slighty increased linewidth:
        n_shades = 10

        diff_linewidth = 1.05
        alpha_value = 0.3 / n_shades
        for n in range(1, n_shades+1):
            ax.plot(marker='o',
                    linewidth=2+(diff_linewidth*n),
                    alpha=alpha_value,
                    legend=False,
                    ax=ax,
                    color=colors)
        # Color the areas below the lines:
        for column, color in zip(df, colors):
            ax.fill_between(x=df.index,
                            y1=df[column].values,
                            y2=[0] * len(df),
                            color=color,
                            alpha=0.1)
        ax.grid(color='#2A3459')
        ax.set_xlim([ax.get_xlim()[0] - 0.2, ax.get_xlim()[1] + 0.2])  # to not have the markers cut off
        ax.set_ylim(0)
        self.canvas.draw()



import ui
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    blood = QtWidgets.QMainWindow()
    ui = Ui_blood()
    ui.setupUi(blood)
    blood.show()
    sys.exit(app.exec_())
